tests/test_home.py::HomeTest::test_menu_link
--------------------------------------------------------------------
Last Page: https://practice.automationbro.com/my-account/
  Browser: chrome (104.0.5112.102)
   Driver: chromedriver (104.0.5112.79)
Timestamp: 1662024855  (Unix Timestamp)
     Date: Thursday, 1 September 2022
     Time: 10:34:15 AM  (GMT Summer Time, UTC+00)
--------------------------------------------------------------------
Traceback: File "C:\Users\rekla\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "C:\Users\rekla\AppData\Local\Programs\Python\Python310\lib\unittest\case.py", line 549, in _callTestMethod
    method()
  File "C:\PycharmProjects\pythonProject\seleniumBase\tests\test_home.py", line 44, in test_menu_link
    self.assertEqual(expected_links[idx], link_el.text)
Exception: list index out of range